name: deepdisc

channels:
  - conda-forge
  - defaults

dependencies:
  - astropy
  - ipykernel
  - imgaug
  - numpy
  - pybind11
  - pip:
    - timm
    - autograd
    - peigen
    - proxmin
    - opencv-python-headless